# Generated by Django 3.2.16 on 2023-03-13 17:42

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_last_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('follower', 'followed'), name='subscription_uniqueness'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('followed', django.db.models.expressions.F('follower')), _negated=True), name='self_follow_not'),
        ),
    ]
