version: '3.3'
services:
# deploying settings
  backend:
    image:
      damirkasimov/diploma:latest
    restart: always
    volumes:
     - media_value:/app/media/
    env_file:
     - ./.env
   # ports:
   #  - "8000:8000"
  frontend:
    image:
      damirkasimov/frontend_vm:good
    volumes:
      - ../frontend/:/app/result_build/
 
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
      - "8000:80"
   #   - "80:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media_value:/var/html/media/
    restart:
      always
volumes:
  media_value:
