
name: 17 sprint Diploma deploy

on: [push]

jobs:
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
  #  if: github.ref == 'refs/heads/master'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        # Вызов сборщика контейнеров docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 
      - name: Login to Docker 
        # Запуск скрипта авторизации на Docker Hub
        uses: docker/login-action@v1 
        with:
          username: damirkasimov
          password: madagaskar123
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2 
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
         # repository: damirkasimov/yamdb_final
          #tag_with_ref: true
          tags: damirkasimov/diploma:latest
  pull/deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
    - name: executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY_VM }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          # Выполняет pull образа с DockerHub
          sudo docker pull damirkasimov/diploma:latest
        #  #остановка всех контейнеров
        #  sudo docker stop $(sudo docker ps -a -q)
        #  sudo docker run --rm -d -p 5000:5000 damirkasimov/diploma:latest

